default_stages:
- commit
repos:
# general hooks to verify or beautify code
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=100000]
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: detect-aws-credentials
    args: [--allow-missing-credentials, --credentials-file, docker-compose/.env]
  - id: detect-private-key
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix]
  - id: requirements-txt-fixer


# autodelete unused imports
- repo: https://github.com/hadialqattan/pycln
  rev: v1.1.0
  hooks:
    - id: pycln
      args: [ --all ]


# autoformat code with black formatter
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    files: ^(ais|tests)
    args: [-l 120]


# beautify and sort imports
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
  - id: isort
    files: ^(ais|tests)
    args: ["--profile", "black"]

# check code style
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    files: ^(ais|tests)
    args: [--config, ais/.flake8]